spring:
  cloud:
    gateway:
      routes:
      - id: product.service
        uri: lb://product.service
        predicates:
          - Path=/api/product/**
        filters:
          - StripPrefix=2
      - id: items.service
        uri: lb://items.service
        predicates:
          - Path=/api/items/**
        filters:
          - StripPrefix=2
          